# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Storyline' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!

  # Pods for Storyline

  target 'StorylineTests' do
    #inherit! :search_paths
    pod 'Firebase/Core'
    pod 'Firebase/Messaging'
    pod 'Firebase/Crash'
    # Pods for testing
  end

end
